version: "3.8"

services:
  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=production
    command: uvicorn modelo_app_html:app --host 0.0.0.0 --port 8000 --reload
