# Usamos la imagen oficial de Python
FROM python:3.10-slim

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos el archivo de dependencias
COPY requirements.txt .

# Instalamos las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos todos los archivos del proyecto
COPY . .

# Exponemos el puerto 8000
EXPOSE 8000

# Comando para ejecutar FastAPI con Uvicorn
CMD ["uvicorn", "modelo_app_html:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
